### ISSUE TITLE
after_merging2_label_ids?

### ISSUE THREAD

**Issue by tonghe90** [daerduoCarey/partnet_seg_exps#1]
is this correct [after_merging2_label_ids](https://github.com/daerduoCarey/partnet_seg_exps/blob/a9ad98bcadec45748dee6dada9d41160aaadd29d/exps/ins_seg_sgpn/train.py#L63) ?

**Comment by daerduoCarey** [comment]
Hi, Tong,

Thank you for pointing it out! I forgot to modify this. Just changed it to after_merging_label_ids.

Best,
Kaichun
