### ISSUE TITLE
Preprocessing for Testing on Custom Data

### ISSUE THREAD

**Issue by cravisjan97** [daerduoCarey/partnet_seg_exps#10]
I would like to use the model trained on ``` partnet dataset for instance segmentation``` on my own Chair dataset. What pre-processing should I do on the input point clouds to match the partnet distribution/get good results?

**Comment by daerduoCarey** [comment]
Just prepare your data in the provided partnet hdf5 file format. Normalize the data in the same way: 1) consistently oriented with y-up, z-front, x-right; 2) normalize the shape to be within a unit-sphere; 3) make sure the point count roughly match the partnet.
