### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'log_Chair_level_3/visu/epoch-004/pts/shape-00.png'

### ISSUE THREAD

**Issue by mtli77** [daerduoCarey/partnet_seg_exps#11]
Hi @daerduoCarey 
I miss this bug during the training process of the `ins_seg_detection`
```
2020-12-29 21:25:21.728187
Reading data from  ../../data/ins_seg_h5_for_detection/Chair-3/val-00.h5
/bin/sh: 1: RenderShape: not found                                                                                 |
Traceback (most recent call last):
  File "train.py", line 506, in <module>
    train()
  File "train.py", line 221, in train
    eval_one_epoch(sess, ops, test_writer, epoch)
  File "train.py", line 483, in eval_one_epoch
    per_shape_seg_loss_val[:end_idx-start_idx, ...], per_shape_l21_norm_val[:end_idx-start_idx, ...], conf_gt[:end_idx-start_idx, ...], conf_pred[:end_idx-start_idx, ...])
  File "train.py", line 340, in gen_visu
    render_pts(out_fn, cur_pts)
  File "/disk/tia/partnet_seg_exps/exps/ins_seg_detection/../utils/geometry_utils.py", line 403, in render_pts
    img = np.array(misc.imread(out), dtype=np.float32)
  File "/home/ubuntu/.conda/envs/tia37/lib/python3.7/site-packages/numpy/lib/utils.py", line 100, in newfunc
    return func(*args, **kwds)
  File "/home/ubuntu/.conda/envs/tia37/lib/python3.7/site-packages/scipy/misc/pilutil.py", line 164, in imread
    im = Image.open(name)
  File "/home/ubuntu/.conda/envs/tia37/lib/python3.7/site-packages/PIL/Image.py", line 2891, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'log_Chair_level_3/visu/epoch-004/pts/shape-00.png'
```
I use the data-file `ins_seg_h5_for_detection`which is directly unzipped from the `ins_seg_h5.zip`.
So, where are the `*.png` files?

Best regards!

**Comment by 17853333982** [comment]
I have the same problem. Have you solved it?

**Comment by Lizhinwafu** [comment]
> Hi @daerduoCarey
> I miss this bug during the training process of the `ins_seg_detection`
> 
> ```
> 2020-12-29 21:25:21.728187
> Reading data from  ../../data/ins_seg_h5_for_detection/Chair-3/val-00.h5
> /bin/sh: 1: RenderShape: not found                                                                                 |
> Traceback (most recent call last):
>   File "train.py", line 506, in <module>
>     train()
>   File "train.py", line 221, in train
>     eval_one_epoch(sess, ops, test_writer, epoch)
>   File "train.py", line 483, in eval_one_epoch
>     per_shape_seg_loss_val[:end_idx-start_idx, ...], per_shape_l21_norm_val[:end_idx-start_idx, ...], conf_gt[:end_idx-start_idx, ...], conf_pred[:end_idx-start_idx, ...])
>   File "train.py", line 340, in gen_visu
>     render_pts(out_fn, cur_pts)
>   File "/disk/tia/partnet_seg_exps/exps/ins_seg_detection/../utils/geometry_utils.py", line 403, in render_pts
>     img = np.array(misc.imread(out), dtype=np.float32)
>   File "/home/ubuntu/.conda/envs/tia37/lib/python3.7/site-packages/numpy/lib/utils.py", line 100, in newfunc
>     return func(*args, **kwds)
>   File "/home/ubuntu/.conda/envs/tia37/lib/python3.7/site-packages/scipy/misc/pilutil.py", line 164, in imread
>     im = Image.open(name)
>   File "/home/ubuntu/.conda/envs/tia37/lib/python3.7/site-packages/PIL/Image.py", line 2891, in open
>     fp = builtins.open(filename, "rb")
> FileNotFoundError: [Errno 2] No such file or directory: 'log_Chair_level_3/visu/epoch-004/pts/shape-00.png'
> ```
> 
> I use the data-file `ins_seg_h5_for_detection`which is directly unzipped from the `ins_seg_h5.zip`.
> So, where are the `*.png` files?
> 
> Best regards!

I have the same problem. Have you solved it?

**Comment by daerduoCarey** [comment]
This is for visualization only. Feel free to remove the render_pts calls. If you want to render the images, you need to install Thea: https://github.com/sidch/thea, or replace it with other viz tools, e.g. matplotlib.
