### ISSUE TITLE
settings file for semantic segmentation

### ISSUE THREAD

**Issue by lodurality** [daerduoCarey/partnet_seg_exps#2]
Hi, I am trying to run your experiments for semantic segmentation and it looks like settings file (for arg --setting) is missing. Can you navigate me where to find it?

The script I am trying to run:
https://github.com/daerduoCarey/partnet_seg_exps/blob/master/exps/sem_seg_pointcnn/train_val_seg.py

**Comment by daerduoCarey** [comment]
I just added two bash scripts in the repo. Haven't tested them yet. But should be good to go.

**Comment by lodurality** [comment]
Thank you!

**Comment by lodurality** [comment]
Bash scripts don't work for semantic segmentation

`ModuleNotFoundError: No module named 'partnet_sem_seg'`

Probably models folder is missing for semantic segmentation?

**Comment by daerduoCarey** [comment]
Great question. Sorry that I forgot to test the code when releasing it. I just tested and updated the codebase. It should work this time. Don't forget to compile sampling tf_op.

**Comment by lodurality** [comment]
Everything works (with tensorflow 1.12). Thank you!
