### ISSUE TITLE
removing class 0 from evaluation

### ISSUE THREAD

**Issue by lodurality** [daerduoCarey/partnet_seg_exps#4]
Am I correct that you are removing class zero from evaluation since it is for rare parts (line 124 in test_general_seg.py)? 

`seg_res = np.argmax(seg_probs[:, :, 1:], axis=-1) + 1`

And just to confirm: are all results in the paper reported without this category (both shape mIOU and part-category mIOU)?

**Comment by daerduoCarey** [comment]
Yes

**Comment by lodurality** [comment]
Thanks!

**Comment by LiyaoTang** [comment]
Hi @daerduoCarey ,

Sorry for continuing on this. But does it mean that we can treat the 0-labeled points as unlabeled points?
